name: coverity-scan

on:
  workflow_dispatch:
  
jobs:
  coverity:
    runs-on:
      - self-hosted
      - cov-analysis
    
    steps:
       - uses: actions/checkout@v3
       
       - name: Coverity Scan
         run: |
          export PATH=/opt/cov-analysis-2022.6.0/bin:$PATH
          cd /home/ubuntu/NASA-HDTN/HDTN/build
          make clean
          
          # Coverity Build
          cov-build --dir idir make -j8
          
          #Coverity Analyze
          cov-analyze --dir idir --all --enable-constraint-fpp --enable-fnptr --enable-virtual --strip-path /home/ubuntu/NASA-HDTN/HDTN
        
